### ISSUE TITLE
Embycon (w/Up Next Addon) marking unwatched episode as watched

### ISSUE THREAD

**Issue by nikhillfc** [faush01/plugin.video.embycon#111]
I use Up Next addon along with Embycon. When I hit "Watch Next Episode" just before the end of an ongoing episode, the next episode plays just fine... however if I immediately stop the video after that, that episode gets marked as watched. The 'TV Shows - Next Episodes (20)' section of Embycon then shows the subsequent episode in the list (essentially skipping over an episode)

I thought both Embycon and Up Next are sending play next episode command one after the other, but don't think that's the case as I've disabled Play Next inside Embycon. I raised this issue with Up Next dev but he said episodes being marked as watched is done by Embycon

(As to why I don't use the native Play Next with Embycon, its because the Play Next message never pops up while the video is still playing... it does only when an episode completely ends (skin: arctic zephyr 2)

Thanks in advance!
Log File: https://paste.kodi.tv/ilowumuyiz

**Comment by faush01** [comment]
The EmbyCon addon does not "mark" things watched, it reports it playback position and the Emby server will mark the item played if the position when stopped is far enough through the media.

The first thing to check is that your episodes have a runtime/duration, you can do this in the web interface when viewing the details about an episode, it should be at the top of the page just under the title:
![image](https://user-images.githubusercontent.com/3616162/107578256-a1534980-6c47-11eb-9021-b0381b6f240c.png)
If the episode that got instantly marked as watched has a duration then it might be a bug with some sort of weird interaction between the next up and embycon addon.

Yes that is correct the play next EmbyCon native feature waits until the end and playback stops, this is due to the fact end credits are unpredictable and all you need to do is hit stop or skip forward for the native play next dialog to show. I find this is a much better experience than having the Play next pop up too soon or to late.

**Comment by nikhillfc** [comment]
Hmmm. All the episodes I tested with (How I Met Your Mother or Friends), they do have a proper runtime, so as you say it could be some interaction with Up Next and Embycon.

I'd rather use Embycon's native Play Next to be honest. You're right about unpredictability and you could keep it the way it is by default... but an option to show the message 30 seconds before an episode would be great...!

**Comment by faush01** [comment]
Try setting "Play next episode at time left" to 30
Its in the EmbyCon settings under Events.

**Comment by nikhillfc** [comment]
Yeah I thought that's what it was for, but unfortunately it still shows up after the end of the video, and not 30 seconds before...

**Comment by faush01** [comment]
Did you restart Kodi after you set this?
If it was zero before and you set it to say 30 you need to restart Kodi for the play next service to start up.

**Comment by nikhillfc** [comment]
Just did so. Weird thing is, it sort of acts like my original problem. 

I played Episode 1, it didn't show up 30 seconds before it ended, it only showed up after the end of episode. I hit Play Next, but as soon as Episode 2 started, it showed up again asking to play Episode 3.

Anyway, I made it 0 again. It's fine I guess. Only thing I'd add is, if the user doesn't select anything, Play Next should continue to play next episode after non selection for 10-15 seconds. Otherwise, if I want to have something play in the background while I work, I have to keep manually selecting Play Next.

Thanks a lot for your time though! It's a great addon nonetheless

**Comment by faush01** [comment]
This is probably a bug, it looks like if you have both
"Play next episode at time left" > 0
and
"Play next episode after %" < 100

Then you will get both Play next dialogs, one when it hits x seconds to the end and then when you select next it pops up the on stop action which triggers the play next dialog again.

Just set the "Play next episode after %" = 100
and you wont see the two dialogs.
