### ISSUE TITLE
Videos auto-playing again after manual stop

### ISSUE THREAD

**Issue by bubblesnout** [faush01/plugin.video.embycon#59]
Having a strange issue since installing EmbyCon which I can't figure out. When I stop a video that is currently playing (whether it is an EmbyCon video or otherwise) after a number of seconds (20-30 or so) the video that was playing begins playing again. The time between stopping the video and the video auto-playing doesn't seem to be exactly the same each time.

I've turned on debug logging, you can see my Kodi log here: https://www.dropbox.com/s/723gltwzvnyhqy7/kodi.log?dl=0

The series of events in the log:
Played initial video: 20:54:25
Stopped video: 20:54:45
Video automatically started again: 20:55:04

I've tried disabling EmbyCon and the behaviour disappears. My guess is it's something to do with some sort of update process that runs when playback is stopped that incorrectly calls the last media to play again (or something).

**Comment by bubblesnout** [comment]
Note I’m using the dev version of EmbyCon but this same behaviour was occurring with the stable version.

Another strange happening that may or may not be related, when I pause a video after a similar period of time (20-30 seconds, sometimes longer) the video stops and I’m returned to the previous screen/menu.

**Comment by faush01** [comment]
On the auto replay thing, I have seen some skins do weird things when refreshing containers, what skin are you using? Can you switch back to the default skin and try again and see if the restart play issues is still there.

Auto stop on screensaver is an option in embycon, you can turn it off in the options.

**Comment by bubblesnout** [comment]
Gotcha, sorry I missed that setting. 

I’m using Estuary Mod which is a customisable version of the default Estuary skin. I’ve just tried back on the default skin and the problem seems to have disappeared. Haven’t seen it happen since using EmbyCon though so it’s a little weird.

**Comment by bubblesnout** [comment]
Estuary Mod V2: https://forum.kodi.tv/showthread.php?tid=306757

**Comment by faush01** [comment]
That is the skin I was talking about when it said some skins do some weird container refresh action that actually calls the items and in EmbyCon this triggers a play action even if the item is off screen. I looked at this skin a year or so ago for this exact issue and found the root cause but the skin author was not interested in altering the skin.

Perhaps I should try to add detection for this in EmbyCon, I will revisit and see how valid the skin action is and if EmbyCon should work in this scenario I will try to fix it.

Until then use the Estuary skin cloning addon or use Estuary
https://emby.media/community/index.php?/topic/49724-support-thread-embuary-a-emby-kodi-skin/
Or
https://emby.media/community/index.php?/topic/58367-embycon-estuary-skin-cloner/

**Comment by bubblesnout** [comment]
Thanks for that, shame they weren't interested in fixing the problem on their end.

I've just had a look at the Embuary skin and I actually quite like it, I'll see if I can get it customised to my liking. Thanks for the suggestion!
