### ISSUE TITLE
Feature Request: Trakt (or TMDB lists) integrated with Embycon

### ISSUE THREAD

**Issue by nikhillfc** [faush01/plugin.video.embycon#72]
Hi, I use Embycon connected to a huge remote library, and I would like my Kodi home page to just pull lists from my trakt lists. For example I have liked lists like 'Netflix shows', 'HBO shows', 'Disney+ shows' etc. on trakt. So now I could create widgets in Embuary that pull these lists directly to my home page and when I click on an item it takes me to play the show from the Embycon add-on.

I believe lots of streaming video add-ons already do this...

Doesn't even have to be trakt lists though. It could be tmdb lists or any other. Possible? 

Thanks for your work. It really is amazing.

**Comment by faush01** [comment]
This could be possible if you tagged or created play lists on Emby with your list of items.
This really the only way as EmbyCon just uses data from the Emby Server and the Emby Server would have to control this.
The current way lists are done on Emby Server is using Playlists and Tags.

I have just added Tags as an option to the EmbyCon Movie menus so that might help.

The big question is how to you get your lists into Emby as playlists or Tags on Movies. That I don't know the best way, perhaps someone on the forum knows.

**Comment by nikhillfc** [comment]
Ah ok I see why it would be a problem and that Embycon doesn't act like any other streaming video add-ons out there...

The problem is I cannot do that on the Emby server side as I do not own it. It would however have been lot easier if Emby server itself allowed trakt integration with support for lists I guess. Right now all it does is it syncs with trakt to "track" shows and movies. It's useless :(

Thanks for your time though!

Thanks for the reply though.

**Comment by faush01** [comment]
Yeah EmbyCon is just a client for Emby, Emby needs to populate the lists and yes I agree the trakt plugin is the place for this to happen.
